### PR TITLE
Support GHC-9.8.1

### PR DESCRIPTION
**Pull request by TeofilC**
Adds support for GHC 9.8.1.

This depends on this MR:
- https://github.com/haskell/ghc-events/pull/102

### CODE REVIEW

**Comment by BinderDavid** [comment]
Looks good! But I am a bit surprised that the CI for 9.8.1 already runs through: If I understood correctly the released version of ghc-events still has a base upper-bound of `<0.19` 🤔 , so it should only run through once a new ghc-events version is available.

**Review by BinderDavid — APPROVED** [review]

**Comment by TeofilC** [comment]
> Looks good! But I am a bit surprised that the CI for 9.8.1 already runs through: If I understood correctly the released version of ghc-events still has a base upper-bound of `<0.19` 🤔 , so it should only run through once a new ghc-events version is available.

That's because I've also temporarily added an allow-newer pragma to the cabal.project until a new version/revision of ghc-events is released.

**Comment by BinderDavid** [comment]
Ah, I saw that line but I guess that I misunderstood the semantics of `allow-newer`. I thought that this only allows to pick a version of `ghc-events` that is greater than the upper bound that the cabal file allows.

Do you want to merge this now or should we wait for a new release of ghc-events?

**Comment by TeofilC** [comment]
Yeah I find that confusing too. I think if I had it without the `:*` then it would be what you mention (IIRC).

It's up to you, but my preference is to wait.

**Comment by TeofilC** [comment]
This is unblocked now. I've removed the allow-newer and it should be good to go

**Comment by BinderDavid** [comment]
Thanks!

**Pull request merged**
