### PR TITLE
Switch to ghc-events 0.13.0

### LINKED ISSUE #125: Switch to ghc-events 0.13
Ghc-events 13.0 introduces a breaking change by switching from String to Text.
Also fixes problems with utf-8 decoding and compatibility with GHC 8.10.1.

See: https://github.com/haskell/ghc-events/pull/55

### PR DESCRIPTION
**Pull request by BinderDavid**
Fix #125

### CODE REVIEW

**Comment by BinderDavid** [comment]
I'm not sure whether this should be blocked by this: https://github.com/haskell/ghc-events/pull/62

**Comment by BinderDavid** [comment]
I'm not sure whether this PR should be blocked by this: https://github.com/haskell/ghc-events/pull/62

It seems that the bug in ghc-events 0.13.0 is in a function which writes files to disk, not in the parsing part.

**Comment by expipiplus1** [comment]
That ghc-events PR has been merged now FYI

**Comment by ocharles** [comment]
I think this can be closed now: https://github.com/mpickering/eventlog2html/commit/ad06251c919ee3feaa57e5e1aecdad34de096059#diff-7470bcde200e980c19be6f8fbd32abea3d07c7fc5b203ee0df06e8772328daaa

**Pull request closed without merging**
