### PR TITLE
Show metadata

### PR DESCRIPTION
**Pull request by BinderDavid**
Print the commandline arguments that the program was invoked with in the header of the Html file.

### CODE REVIEW

**Comment by BinderDavid** [comment]
This partially resolves #15, but we cannot currently use the hDate field from the header, since this field is set to "aaa" in eventlog mode.

**Comment by mpickering** [comment]
I'm not sure there is currently a way to get the date from an eventlog. I'll ask Ben.

**Comment by mpickering** [comment]
I'll fix CI for the documentation. You should be able to build the docs locally as well though, or at least be able to build the site generator. `cabal new-build hakyll-eventlog`.

**Comment by mpickering** [comment]
Pushed this directly to master seeing as I couldn't push to your branch.

**Pull request closed without merging**
